# Generated by Django 2.1.2 on 2018-10-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
